name: Build Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make llvm clang git unzip

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Get iOS SDK
        run: |
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          
      - name: Get Toolchain (Compiler)
        run: |
          curl -LO https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64-10.0.0.tar.gz
          mkdir -p $HOME/theos/toolchain/linux/iphone
          tar -xf linux-ios-arm64-10.0.0.tar.gz -C $HOME/theos/toolchain/linux/iphone --strip-components=1

      - name: Build .deb
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CriticalChams_Final
          path: packages/*.deb
