name: Build Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make llvm clang git

      - name: Setup Theos
        run: |
          git clone --recursive --depth 1 https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Get iOS SDK (Surgeon Mode)
        run: |
          # Create the folder
          mkdir -p $HOME/theos/sdks
          cd $HOME/theos/sdks
          
          # Initialize an empty git repo
          git init
          git remote add origin https://github.com/theos/sdks.git
          
          # Tell git we only want ONE specific folder (iPhoneOS14.5.sdk)
          git config core.sparseCheckout true
          echo "iPhoneOS14.5.sdk" >> .git/info/sparse-checkout
          
          # Pull ONLY that folder (This is tiny and won't crash)
          git pull --depth=1 origin master
          
      - name: Get Toolchain
        run: |
          curl -LO https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64-10.0.0.tar.gz
          mkdir -p $HOME/theos/toolchain/linux/iphone
          tar -xf linux-ios-arm64-10.0.0.tar.gz -C $HOME/theos/toolchain/linux/iphone --strip-components=1

      - name: Build .deb
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CriticalChams_Final
          path: packages/*.deb
