name: Build Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sbingner/theos:latest  # This computer already has Theos installed!
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Trust Git Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build the Cheat
        run: |
          export THEOS=/opt/theos
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CriticalChams_Final
          path: packages/*.deb
